name: donation_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.12.4
  flutter_dotenv: ^5.1.0
  image_picker: ^0.8.7+5
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/image/CureNurture_logo.png
    - lib/assets/image/gradient_background.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/image/fonts/Montserrat-Regular.ttf
        - asset: lib/assets/image/fonts/Montserrat-Bold.ttf
          weight: 700
