// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCX76TriYqQZF9UYFqjnjemwJq1aKkx7A',
    appId: '1:375508367899:web:1bedb95d726fb753a756be',
    messagingSenderId: '375508367899',
    projectId: 'curenurture',
    authDomain: 'curenurture.firebaseapp.com',
    storageBucket: 'curenurture.firebasestorage.app',
    measurementId: 'G-XF11QCC021',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRp0UbBQhjkmv9tWXETBtc1L2DPB-mk0w',
    appId: '1:375508367899:android:a7a75dc8de17d95ea756be',
    messagingSenderId: '375508367899',
    projectId: 'curenurture',
    storageBucket: 'curenurture.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoTLKezJSnurdDmv6saZ6jeIVM-qcHzIA',
    appId: '1:375508367899:ios:5f0c28155feb2707a756be',
    messagingSenderId: '375508367899',
    projectId: 'curenurture',
    storageBucket: 'curenurture.firebasestorage.app',
    iosBundleId: 'com.dialysis.dialysisPatientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoTLKezJSnurdDmv6saZ6jeIVM-qcHzIA',
    appId: '1:375508367899:ios:5f0c28155feb2707a756be',
    messagingSenderId: '375508367899',
    projectId: 'curenurture',
    storageBucket: 'curenurture.firebasestorage.app',
    iosBundleId: 'com.dialysis.dialysisPatientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCX76TriYqQZF9UYFqjnjemwJq1aKkx7A',
    appId: '1:375508367899:web:2814502f005fbb6aa756be',
    messagingSenderId: '375508367899',
    projectId: 'curenurture',
    authDomain: 'curenurture.firebaseapp.com',
    storageBucket: 'curenurture.firebasestorage.app',
    measurementId: 'G-NQFY14MW9R',
  );
}
